title: xalmaier's GitHub page
description: Welcome to my website

remote_theme: jekyll/minima
plugins:
  - jekyll-remote-theme

header_pages:
  - tutorials.md
  - about.md
  - contact.md

minima:
  skin: auto
